__author__ = 'Derek Payton <derek.payton@gmail.com>'
__maintainer__ = 'blag <blag@users.noreply.github.com>'
__copyright__ = 'Copyright (c) Derek Payton, blag'
__description__ = 'A fake Django admin login screen to notify admins of attempted unauthorized access.'
__version__ = '1.2.0'
__license__ = 'MIT'
