---
name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental: 
          - false
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

        django:
          - "2.2"
          - "3.0"
          - "3.1"
          - "3.2"
        include:
          - django: "4.0"
            experimental: true
            continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          pip install Django==${{ matrix.django }} django-ipware
          pip install pytest pytest-cov pytest-django pytest-flake8 pytest-pythonpath
      - name: Run tests
        run: |
          py.test tests/ --cov=admin_honeypot --cov-config=.coveragerc --cov-report=xml --flake8=admin_honeypot
      - name: ls
        run: |
          ls -R
      # - name: Upload coverage results to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./.coverage
      #     name: codecov-umbrella
      #     path_to_write_report: ./.coverage/codecov_report.txt
      #     verbose: true
